### ISSUE TITLE
Request Failed - /repos/{owner}/{repo}/vulnerability-alerts

### ISSUE THREAD

**Issue by brunopenso** [octokit/core.js#208]
HI,

I`m using the @octokit/core version 3.1.2 to execute this request:
```node
      await octokit.request('GET /repos/{owner}/{repo}/vulnerability-alerts', {
        owner: 'myorg',
        repo: 'myrepo',
        mediaType: {
          previews: [
            'dorian'
          ]
        }
      })
```

And I'm getting this error:
```bash
RequestError [HttpError]: Resource not accessible by integration
        at /Users/myuser/dev/github_vor/node_modules/@octokit/request/dist-src/fetch-wrapper.js:49:31
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at sendRequestWithRetries (/Users/myuser/dev/github_vor/node_modules/@octokit/auth-app/dist-src/hook.js:56:16)
        at Object.getRepoInfo (/Users/myuser/dev/github_vor/src/github/repo.js:98:7)
        at Object.<anonymous> (/Users/myuser/dev/github_vor/tests/integration/github.test.js:42:20) {
      status: 403,
      headers: {
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
        connection: 'close',
        'content-encoding': 'gzip',
        'content-security-policy': "default-src 'none'",
        'content-type': 'application/json; charset=utf-8',
        date: 'Fri, 09 Oct 2020 21:30:59 GMT',
        'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
        server: 'GitHub.com',
        status: '403 Forbidden',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
        'transfer-encoding': 'chunked',
        vary: 'Accept-Encoding, Accept, X-Requested-With',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'deny',
        'x-github-media-type': 'github.dorian-preview; format=json',
        'x-github-request-id': 'DE70:16FC:3DD981:66C6C5:5F80D693',
        'x-ratelimit-limit': '15000',
        'x-ratelimit-remaining': '14997',
        'x-ratelimit-reset': '1602282658',
        'x-ratelimit-used': '3',
        'x-xss-protection': '1; mode=block'
      },
      request: {
        method: 'GET',
        url: 'https://api.github.com/repos/myorg/myrepo/vulnerability-alerts',
        headers: {
          accept: 'application/vnd.github.dorian-preview+json',
          'user-agent': 'octokit-core.js/3.1.2 Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/16.4.0',
          authorization: 'token [REDACTED]'
        },
        request: { hook: [Function: bound bound register] }
      },
      documentation_url: 'https://docs.github.com/rest/reference/repos#check-if-vulnerability-alerts-are-enabled-for-a-repository'
    }
```

When I use the same logic on the postman interface it works just fine:

https://api.github.com/repos/myorg/myrepo/vulnerability-alerts

The difference between both requests are:
- Postman: I'm using a PAT associated with my account
- octokit: I'm using an application authentication

For reference, the request below works fine:
```node
    const repo = await github.app.request('GET /repos/:owner/:repo/topics', {
      owner: temp[0],
      repo: temp[1],
      mediaType: {
        previews: [
          'mercy'
        ]
      }
    })
```

**Comment by brunopenso** [comment]
HI I changed the app permission on the Repository and Organization settings but the error is the same. 

I will wait more to see if it isn't some kind of cache.

**Comment by gr2m** [comment]
Did you accept the new permissions for that installation? For existing installations, adding new permissions to an app take only effect once you accept the change to each installation, even if you own the app yourself

**Comment by brunopenso** [comment]
Hi,

It worked. The new permissions for installation were sent to the email registred as primary on the account and I was without access.

Now it worked.

Thanks a lot.
