### ISSUE TITLE
[HttpError: Bad credentials] personal token auth to create a gist doesn't work

### ISSUE THREAD

**Issue by mohamedhayibor** [octokit/core.js#254]
**What happened?**
I'm running this, following the [create a gist](https://docs.github.com/en/free-pro-team@latest/rest/reference/gists#create-a-gist) section.

```js
const octokit = new Octokit({
  auth: token
});

await octokit.request('POST /gists', {
  files: saveGist
});
```

This returns: `HttpError: Bad credentials`

**What did you expect to happen?**

This is a straight forward use case. What am I missing?

**Comment by gr2m** [comment]
Most likely the token does not have the “gist” scope. Can you log the full error?

**Comment by mohamedhayibor** [comment]
```
HttpError: Bad credentials
    at /Users/mo/..../note/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /Users/mo/..../note/cli.js:94:5
```

+ I only specifically allowed the "gist" scope.

**Comment by gr2m** [comment]
I was not able to reproduce the problem.

```js
const octokit = new Octokit({
  auth: "MY TOKEN",
});

octokit
  .request("POST /gists", {
    files: {
      "test.txt": {
        content: "test",
      },
    },
  })
  .then(console.log, console.log);
```

Here is the gist it created

https://gist.github.com/gr2m/8941225b4aa0e8136b35911915beca9e

Can you please log the error and share what it says?

```js
await octokit.request('POST /gists', {
  files: saveGist
}).catch(console.log)
```

**Comment by mohamedhayibor** [comment]
```
RequestError [HttpError]: Bad credentials
    at /Users/mo/..../note/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 401,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '80',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 24 Nov 2020 09:06:41 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '401 Unauthorized',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'D0C7:9CC2:735169:904C40:5FBCCD21',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '54',
    'x-ratelimit-reset': '1606211195',
    'x-ratelimit-used': '6',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/gists',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.2.1 Node.js/15.2.1 (darwin; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"files":{"test.txt":{"content":"test"}}}',
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest'
}
```

I tried with a new token `only allowed gists`, same problem.

Thanks a lot for taking a look btw.

**Comment by gr2m** [comment]
Can you try to reproduce the problem using `curl`?

Try

```
curl -XPOST -H"Authorization: token [TOKEN HERE]" https://api.github.com/gist -d ''{"files":{"test.txt":{"content":"test"}}}''
```

If you still see the error, I'd suggest to contact support: support.github.com/contact. You can reference this issue and share the request ID: `D0C7:9CC2:735169:904C40:5FBCCD21`. They have tools to look it up and find out exactly what is happening. I'm out of ideas I'm afraid

**Comment by mohamedhayibor** [comment]
Tried the curl with my token, it spits out:

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
```

Thank you very much. I contacted support and referenced the issue.

**Comment by kwacky1** [comment]
> ```
> curl -XPOST -H"Authorization: token [TOKEN HERE]" https://api.github.com/gist -d ''{"files":{"test.txt":{"content":"test"}}}''
> ```

That should be `gists` not `gist` 😉  -- hence the "Not Found"

```
curl -XPOST -H"Authorization: token [TOKEN HERE]" https://api.github.com/gists -d '{"files":{"test.txt":{"content":"test"}}}'
```

**Comment by gr2m** [comment]
oopsie, thanks Simon! Can you try that again Mohamed?

**Comment by mohamedhayibor** [comment]
Awesome. The curl works. But I still don't know why using the library fails:

```js
const octokit = new Octokit({
  auth: token,
});

octokit.request('POST /gists', {
    files: {
      "test.txt": {
        content: "test"
      }
    }
}).then(console.log, console.log);
```

**Comment by gr2m** [comment]
Try this:

```
octokit
  .request("GET /")
  .then(console.log, console.log);
```

If you get a 404 error, the token is invalid. If it logs the response, look for 

```
    'x-oauth-scopes': 'gist',
```

in the response header. My guess is that either the token you pass in `auth: token` is invalid, or it does not have the `gist` scope.

**Comment by mohamedhayibor** [comment]
Thanks a lot @gr2m

**Comment by nayebare** [comment]
@gr2m help needed please. In trying to access the GITHUB API through the octokit. The GET method is successful but the POST method is not successful via the code. It is only successfully through POST man. Here is my code. Any help is appreciated. Thank you.
`    let octokit = new Octokit({
        Type: "Bearer Token",
        Token: process.env.GITHUB_TOKEN,
    })

    //
    // To create milestones in a repository
    //
    let response = await octokit.request("GET /repos/{owner}/{repo}/milestones",{
            owner: "EcoDevHackathon",
            repo: repo_name,
            title: 'v545344.0',
            state: 'open',
            description: 'Tracking milestone for version 1.0',
            due_on: '2012-10-09T23:39:01Z'
        })`
Response:
```
  data: [
    {
      url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones/7',
      html_url: 'https://github.com/EcoDevHackathon/midimar/milestone/7',
      labels_url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones/7/labels',
      id: 8489504,
      node_id: 'MI_kwDOCGlzcM4AgYog',
      number: 7,
      title: 'v56573.0',
      description: 'Tracking milestone for version 2.0',
      creator: [Object],
      open_issues: 0,
      closed_issues: 0,
      state: 'open',
      created_at: '2022-10-03T10:08:47Z',
      updated_at: '2022-10-03T10:08:47Z',
      due_on: '2012-10-09T07:00:00Z',
      closed_at: null
    }
  ]
```
Code in the POST request:
`    let octokit = new Octokit({
        Type: "Bearer Token",
        Token: process.env.GITHUB_TOKEN,
    })

    //
    // To create milestones in a repository
    //
    let response = await octokit.request("POST /repos/{owner}/{repo}/milestones",{
            owner: "EcoDevHackathon",
            repo: repo_name,
            title: 'v545344.0',
            state: 'open',
            description: 'Tracking milestone for version 1.0',
            due_on: '2012-10-09T23:39:01Z'
        })`

Response from POST request:
  ```
  data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/issues#create-a-milestone'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/16.0.0 (linux; x64)',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"v545344.0","state":"open","description":"Tracking milestone for version 1.0","due_on":"2012-10-09T23:39:01Z"}',
    request: { hook: [Function: bound bound register] }
  }
```

**Comment by timrogers** [comment]
@nayebare Can you try instantiating `Octokit` like this? What you're doing right not doesn't look quite right:

```js
let octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
```

**Comment by nayebare** [comment]
Thank you @timrogers  but still the same error. This is issue is similar to `https://github.com/octokit/oauth-app.js/issues/110` posted by @ed42311. Here is the response i get when i change the code @timrogers 
```
../@octokit/request/dist-node/index.js:88
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^
RequestError [HttpError]: Not Found
    at ../node_modules/@octokit/request/dist-node/index.js:88:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ../../create_milestones.js:45:20 {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones/7',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 
      '
      ETag, 
      Link, 
      Location, 
      Retry-After, 
      X-GitHub-OTP, 
      X-RateLimit-Limit, 
      X-RateLimit-Remaining, 
      X-RateLimit-Used, 
      X-RateLimit-Resource, 
      X-RateLimit-Reset, 
      X-OAuth-Scopes, 
      X-Accepted-OAuth-Scopes, 
      X-Poll-Interval, 
      X-GitHub-Media-Type, 
      X-GitHub-SSO, 
      X-GitHub-Request-Id, 
      Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 03 Oct 2022 12:21:04 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': 'D2E5:57ED:AA55EF:ACC2B5:633AD3B0',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '52',
      'x-ratelimit-reset': '1664801467',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '8',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/issues#update-a-milestone'
    }
  },
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones/7',
    headers: {
      accept: 'application/json',
      'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/16.0.0 (linux; x64)',
      type: 'Bearer Token',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"scope":"repo","title":"v545344.0","state":"open","description":"Tracking milestone for version 1.0","due_on":"2012-10-09T23:39:01Z"}',
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by timrogers** [comment]
If you `console.log(process.env.GITHUB_TOKEN)`, does anything show up?
