### ISSUE TITLE
Tests fail on Node v18

### ISSUE THREAD

**Issue by wolfy1339** [octokit/core.js#489]
```
FAIL test/agent-ca/agent-ca-test.test.ts
  ● custom client certificate › https.Agent({ca})
    error:0A00018E:SSL routines::ca md too weak
       9 |   let server: any;
      10 |   beforeAll((done) => {
    > 11 |     server = createServer(
         |              ^
      12 |       {
      13 |         key: readFileSync(resolve(__dirname, "./localhost.key")),
      14 |         cert: readFileSync(resolve(__dirname, "./localhost.crt")),
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/agent-ca/agent-ca-test.test.ts:11:14)
  ● custom client certificate › https.Agent({ca, rejectUnauthorized})
    error:0A00018E:SSL routines::ca md too weak
       9 |   let server: any;
      10 |   beforeAll((done) => {
    > 11 |     server = createServer(
         |              ^
      12 |       {
      13 |         key: readFileSync(resolve(__dirname, "./localhost.key")),
      14 |         cert: readFileSync(resolve(__dirname, "./localhost.crt")),
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/agent-ca/agent-ca-test.test.ts:11:14)
  ● Test suite failed to run
    TypeError: Cannot read properties of undefined (reading 'close')
      53 |
      54 |   afterAll((done) => {
    > 55 |     server.close(done);
         |            ^
      56 |   });
      57 | });
      58 |
      at Object.<anonymous> (test/agent-ca/agent-ca-test.test.ts:55:12)
```

**Comment by gr2m** [comment]
I don't think this is a production bug, I think it's the self-signed certificates that no longer seem to be compatible with Node 18. I think this is a testing/maintenance issue, not a bug

**Comment by wolfy1339** [comment]
It seems we need to regenerate the certificates with a stronger cipher.

I believe it is related to NodeJS using OpenSSL 3.0 now
https://nodejs.org/en/blog/release/v17.0.0/#openssl-3-0
