### ISSUE TITLE
[BUG]: `No "exports" main defined` in version 6.0.1

### ISSUE THREAD

**Issue by marekdedic** [octokit/core.js#665]
### What happened?

I updated @octokit/core to v6.0.1 and now I get the following error. See skaut/poptavky#1373

### Versions

`@octokit/core` v6.0.1

### Relevant log output

```shell
Error: No "exports" main defined in /home/user/project/node_modules/@octokit/core/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:593:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/user/project/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/user/project/src/octokit.ts:1:1) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We switched to ESM and you need to use the following options in your `tsconfig.json`:
```
"moduleResolution": "node16",
"module": "node16"
```

**Comment by wolfy1339** [comment]
You need to use ESM, right now your are outputting CJS
https://typestrong.org/ts-node/docs/imports#native-ecmascript-modules
